CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(100) NULL,
    PasswordHash NVARCHAR(256) NULL,
    CreatedAt DATETIME NULL DEFAULT GETDATE(),
    Email NVARCHAR(255) NULL
);
